# Data Exploration
In this assignment, I will be importing data on the income and benefits received in each state and conducting a data exploration. I will focus my exploration on the states that have a higher than average percentage of households that receive SNAP benefits and find out if there is a pattern to where in the United States has more households receiving SNAP.

## Importing Data
I will be importing the geopanda module, a geospatial library used by spatial data scientists.

In [99]:
import geopandas as gpd

Next, I will import a shapefile I downloaded from the US Census Bureau COVID-19 Site. 

In [100]:
snap = gpd.read_file('dataexploration/Income_and_Benefits_-_States.shp')

I will check the data type.

In [101]:
type(snap)

geopandas.geodataframe.GeoDataFrame

The datatype confirmed to me that this data had geo spatial information.

To check what the data looks like, I will use the following command.

In [52]:
snap.head()

OBJECTID       GEO_ID    GEO_NAME FIPS_CODE  B11001_001  B11001_0_1  \
0         1  0400000US01     Alabama        01     1860269        6522   
1         2  0400000US02      Alaska        02      253462        1351   
2         3  0400000US04     Arizona        04     2524300        6840   
3         4  0400000US05    Arkansas        05     1152175        4053   
4         5  0400000US06  California        06    12965435       19785   

   DP03_0052E  DP03_0052M  DP03_0053E  DP03_0053M  ...  DP03_0072E  \
0      163312        2676      117629        2606  ...       30638   
1       10230         612        7609         558  ...       15787   
2      170434        2907      111075        2320  ...       46151   
3       93423        2190       74534        1930  ...       21389   
4      656515        5476      573531        5614  ...      442856   

   DP03_0072M  DP03_0074E  DP03_0074M  HOUSELT75K  INCLT75E_C  INCLT75M_C  \
0        1101      269603        3385       68.64     1276947        7745   
1         634       26868         828       48.91      123967        2179   
2        1561      298375        3044       63.35     1599029        8709   
3        1015      146798        2422       71.79      827149        6046   
4        4522     1184714        6430       52.22     6770185       17356   

   DP03_0074P  DP03_007_1                                           geometry  
0        14.5         0.2  MULTIPOLYGON (((-88.08682 30.25987, -88.07486 ...  
1        10.6         0.3  MULTIPOLYGON (((-179.09763 51.22613, -179.1268...  
2        11.8         0.1  POLYGON ((-109.04518 36.99898, -109.04518 36.9...  
3        12.7         0.2  POLYGON ((-89.73310 36.00061, -89.73305 36.000...  
4         9.1         0.1  MULTIPOLYGON (((-118.56454 33.01864, -118.5591...  

[5 rows x 32 columns]

## Data Type
In order to get the dataframe information, I use the info command.

In [103]:
snap.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   OBJECTID    52 non-null     int64   
 1   GEO_ID      52 non-null     object  
 2   GEO_NAME    52 non-null     object  
 3   FIPS_CODE   52 non-null     object  
 4   B11001_001  52 non-null     int64   
 5   B11001_0_1  52 non-null     int64   
 6   DP03_0052E  52 non-null     int64   
 7   DP03_0052M  52 non-null     int64   
 8   DP03_0053E  52 non-null     int64   
 9   DP03_0053M  52 non-null     int64   
 10  DP03_0054E  52 non-null     int64   
 11  DP03_0054M  52 non-null     int64   
 12  DP03_0055E  52 non-null     int64   
 13  DP03_0055M  52 non-null     int64   
 14  DP03_0056E  52 non-null     int64   
 15  DP03_0056M  52 non-null     int64   
 16  DP03_0057E  52 non-null     int64   
 17  DP03_0057M  52 non-null     int64   
 18  DP03_0058E  52 non-null     int64   
 19  DP

Now I can see all the data types of each column

## Data size
To explore my data, I had to learn about what was in my data. 

To check how many rows and columns are in my data, I use the shape function.

In [105]:
snap.shape

(52, 32)

I found that there were 52 rows and 32 columns in this dataset. There are many columns, and I don't need all of them.

## Trimming the Data
Because this dataset has many columns, I wanted to trim to only the data I wanted to use.

I wanted to focus on looking at each state's total household, total households with food stamps/SNAP benefits in the past 12 months, and percentage of households that have SNAP, so I made sure to trim out other data that won't supplement that.|

In [107]:
desired_columns = ['GEO_ID','GEO_NAME','B11001_001','DP03_0074E','DP03_0074P','geometry']
snap[desired_columns]

GEO_ID              GEO_NAME  B11001_001  DP03_0074E  DP03_0074P  \
0   0400000US01               Alabama     1860269      269603        14.5   
1   0400000US02                Alaska      253462       26868        10.6   
2   0400000US04               Arizona     2524300      298375        11.8   
3   0400000US05              Arkansas     1152175      146798        12.7   
4   0400000US06            California    12965435     1184714         9.1   
5   0400000US08              Colorado     2113387      168243         8.0   
6   0400000US09           Connecticut     1367374      167022        12.2   
7   0400000US10              Delaware      357765       41634        11.6   
8   0400000US11  District of Columbia      281322       39043        13.9   
9   0400000US12               Florida     7621760     1080766        14.2   
10  0400000US13               Georgia     3709488      506957        13.7   
11  0400000US15                Hawaii      456782       50897        11.1   
12  0400000US16                 Idaho      618331       65505        10.6   
13  0400000US17              Illinois     4830038      631076        13.1   
14  0400000US18               Indiana     2553818      272666        10.7   
15  0400000US19                  Iowa     1256855      134125        10.7   
16  0400000US20                Kansas     1124549       90685         8.1   
17  0400000US21              Kentucky     1728681      262173        15.2   
18  0400000US22             Louisiana     1736021      271143        15.6   
19  0400000US23                 Maine      556955       79538        14.3   
20  0400000US24              Maryland     2192518      232090        10.6   
21  0400000US25         Massachusetts     2601914      313019        12.0   
22  0400000US26              Michigan     3909509      551968        14.1   
23  0400000US27             Minnesota     2167801      178604         8.2   
24  0400000US28           Mississippi     1105576      182088        16.5   
25  0400000US29              Missouri     2396271      278848        11.6   
26  0400000US30               Montana      423240       41438         9.8   
27  0400000US31              Nebraska      754063       65237         8.7   
28  0400000US32                Nevada     1075930      130920        12.2   
29  0400000US33         New Hampshire      528078       38059         7.2   
30  0400000US34            New Jersey     3213362      290079         9.0   
31  0400000US35            New Mexico      775651      130965        16.9   
32  0400000US36              New York     7316537     1094793        15.0   
33  0400000US37        North Carolina     3918597      515577        13.2   
34  0400000US38          North Dakota      314903       21741         6.9   
35  0400000US39                  Ohio     4654075      636663        13.7   
36  0400000US40              Oklahoma     1474620      192609        13.1   
37  0400000US41                Oregon     1591835      266999        16.8   
38  0400000US42          Pennsylvania     5025132      663466        13.2   
39  0400000US44          Rhode Island      410885       65655        16.0   
40  0400000US45        South Carolina     1894711      249698        13.2   
41  0400000US46          South Dakota      341565       32624         9.6   
42  0400000US47             Tennessee     2567061      379325        14.8   
43  0400000US48                 Texas     9553046     1167725        12.2   
44  0400000US49                  Utah      957619       69022         7.2   
45  0400000US50               Vermont      259589       31101        12.0   
46  0400000US51              Virginia     3128415      271719         8.7   
47  0400000US53            Washington     2800423      350611        12.5   
48  0400000US54         West Virginia      734676      121943        16.6   
49  0400000US55             Wisconsin     2343129      269631        11.5   
50  0400000US56               Wyoming      230630       13239         5.7   
51  0

To preserve my new dataframe, I will declare it as a new variable.

In [66]:
snap_trimmed = snap[desired_columns].copy()
snap_trimmed

GEO_ID              GEO_NAME  B11001_001  DP03_0074E  DP03_0074P  \
0   0400000US01               Alabama     1860269      269603        14.5   
1   0400000US02                Alaska      253462       26868        10.6   
2   0400000US04               Arizona     2524300      298375        11.8   
3   0400000US05              Arkansas     1152175      146798        12.7   
4   0400000US06            California    12965435     1184714         9.1   
5   0400000US08              Colorado     2113387      168243         8.0   
6   0400000US09           Connecticut     1367374      167022        12.2   
7   0400000US10              Delaware      357765       41634        11.6   
8   0400000US11  District of Columbia      281322       39043        13.9   
9   0400000US12               Florida     7621760     1080766        14.2   
10  0400000US13               Georgia     3709488      506957        13.7   
11  0400000US15                Hawaii      456782       50897        11.1   
12  0400000US16                 Idaho      618331       65505        10.6   
13  0400000US17              Illinois     4830038      631076        13.1   
14  0400000US18               Indiana     2553818      272666        10.7   
15  0400000US19                  Iowa     1256855      134125        10.7   
16  0400000US20                Kansas     1124549       90685         8.1   
17  0400000US21              Kentucky     1728681      262173        15.2   
18  0400000US22             Louisiana     1736021      271143        15.6   
19  0400000US23                 Maine      556955       79538        14.3   
20  0400000US24              Maryland     2192518      232090        10.6   
21  0400000US25         Massachusetts     2601914      313019        12.0   
22  0400000US26              Michigan     3909509      551968        14.1   
23  0400000US27             Minnesota     2167801      178604         8.2   
24  0400000US28           Mississippi     1105576      182088        16.5   
25  0400000US29              Missouri     2396271      278848        11.6   
26  0400000US30               Montana      423240       41438         9.8   
27  0400000US31              Nebraska      754063       65237         8.7   
28  0400000US32                Nevada     1075930      130920        12.2   
29  0400000US33         New Hampshire      528078       38059         7.2   
30  0400000US34            New Jersey     3213362      290079         9.0   
31  0400000US35            New Mexico      775651      130965        16.9   
32  0400000US36              New York     7316537     1094793        15.0   
33  0400000US37        North Carolina     3918597      515577        13.2   
34  0400000US38          North Dakota      314903       21741         6.9   
35  0400000US39                  Ohio     4654075      636663        13.7   
36  0400000US40              Oklahoma     1474620      192609        13.1   
37  0400000US41                Oregon     1591835      266999        16.8   
38  0400000US42          Pennsylvania     5025132      663466        13.2   
39  0400000US44          Rhode Island      410885       65655        16.0   
40  0400000US45        South Carolina     1894711      249698        13.2   
41  0400000US46          South Dakota      341565       32624         9.6   
42  0400000US47             Tennessee     2567061      379325        14.8   
43  0400000US48                 Texas     9553046     1167725        12.2   
44  0400000US49                  Utah      957619       69022         7.2   
45  0400000US50               Vermont      259589       31101        12.0   
46  0400000US51              Virginia     3128415      271719         8.7   
47  0400000US53            Washington     2800423      350611        12.5   
48  0400000US54         West Virginia      734676      121943        16.6   
49  0400000US55             Wisconsin     2343129      269631        11.5   
50  0400000US56               Wyoming      230630       13239         5.7   
51  0

Now I want to filter so that I only have the states whose percentage of total households that receive SNAP are above average in the United States. 

To start off, I have to find the average percentage of total households that receive SNAP.

In [84]:
snappercent = snap_trimmed.DP03_0074P.mean()
snappercent

12.492307692307694

Then, I create a table based on the new query, with only states that have a higher than average percentage of total households that receive SNAP.

In [89]:
snap_greater = snap_trimmed.query("DP03_0074P > 12.492307692307694")
snap_greater

GEO_ID              GEO_NAME  B11001_001  DP03_0074E  DP03_0074P  \
0   0400000US01               Alabama     1860269      269603        14.5   
3   0400000US05              Arkansas     1152175      146798        12.7   
8   0400000US11  District of Columbia      281322       39043        13.9   
9   0400000US12               Florida     7621760     1080766        14.2   
10  0400000US13               Georgia     3709488      506957        13.7   
13  0400000US17              Illinois     4830038      631076        13.1   
17  0400000US21              Kentucky     1728681      262173        15.2   
18  0400000US22             Louisiana     1736021      271143        15.6   
19  0400000US23                 Maine      556955       79538        14.3   
22  0400000US26              Michigan     3909509      551968        14.1   
24  0400000US28           Mississippi     1105576      182088        16.5   
31  0400000US35            New Mexico      775651      130965        16.9   
32  0400000US36              New York     7316537     1094793        15.0   
33  0400000US37        North Carolina     3918597      515577        13.2   
35  0400000US39                  Ohio     4654075      636663        13.7   
36  0400000US40              Oklahoma     1474620      192609        13.1   
37  0400000US41                Oregon     1591835      266999        16.8   
38  0400000US42          Pennsylvania     5025132      663466        13.2   
39  0400000US44          Rhode Island      410885       65655        16.0   
40  0400000US45        South Carolina     1894711      249698        13.2   
42  0400000US47             Tennessee     2567061      379325        14.8   
47  0400000US53            Washington     2800423      350611        12.5   
48  0400000US54         West Virginia      734676      121943        16.6   
51  0400000US72           Puerto Rico     1205075      472397        39.2   

                                             geometry  
0   MULTIPOLYGON (((-88.08682 30.25987, -88.07486 ...  
3   POLYGON ((-89.73310 36.00061, -89.73305 36.000...  
8   POLYGON ((-77.03901 38.79165, -77.03899 38.792...  
9   MULTIPOLYGON (((-82.10512 24.59115, -82.10215 ...  
10  POLYGON ((-83.10862 35.00067, -83.10832 35.000...  
13  POLYGON ((-87.80048 42.49193, -87.79808 42.471...  
17  MULTIPOLYGON (((-89.48530 36.49770, -89.48543 ...  
18  MULTIPOLYGON (((-90.91668 29.04964, -90.91746 ...  
19  MULTIPOLYGON (((-70.60135 42.98109, -70.60783 ...  
22  MULTIPOLYGON (((-83.81617 43.66676, -83.82923 ...  
24  MULTIPOLYGON (((-88.46572 30.20255, -88.45345 ...  
31  POLYGON ((-103.00234 37.00016, -103.00234 37.0...  
32  MULTIPOLYGON (((-74.24656 40.52065, -74.25727 ...  
33  MULTIPOLYGON (((-75.50219 35.32002, -75.52592 ...  
35  MULTIPOLYGON (((-82.70021 41.61220, -82.69113 ...  
36  POLYGON ((-94.61797 36.99891, -94.61799 36.998...  
37  MULTIPOLYGON (((-123.42764 46.22935, -123.4279...  
38  POLYGON ((-74.69492 41.35743, -74.69540 41.357...  
39  MULTIPOLYGON (((-71.55195 41.15173, -71.59370 ...  
40  POLYGON ((-78.54108 33.85112, -78.54109 33.851...  
42  POLYGON ((-83.67540 36.60079, -83.67502 36.600...  
47  MULTIPOLYGON (((-122.63533 47.14821, -122.6391...  
48  POLYGON ((-79.47667 39.72109, -79.47667 39.720...  
51  MULTIPOLYGON (((-66.51535 17.89270, -66.52857 ...

Now I have all the states that are above the average percentage of total households that receive SNAP. 

## Counting Unique Values in a Column
Out of those that that have an above average percentage of total households that receive SNAP, I wanted to see if any of those states had the same percentage. 

In [98]:
snap_greater['DP03_0074P'].value_counts()

13.2    3
13.1    2
13.7    2
15.2    1
16.5    1
15.0    1
16.0    1
16.9    1
16.8    1
12.5    1
13.9    1
39.2    1
16.6    1
15.6    1
14.8    1
14.1    1
12.7    1
14.3    1
14.2    1
14.5    1
Name: DP03_0074P, dtype: int64

From this, I was able to see that 3 states had 13.2%, 2 had 13.1, 2 had 13.7, while other states had unique percentages.

## Plotting
Since I have imported a shapefile, trimmed it, and created a series of queried subsets, I can now visualize my data.

I wanted to see visualize which states had the higher percentage of total households with SNAP, so I used the plot command.

In [94]:
snap_greater.plot()

From this map, I see that more states on the East and South of the United States have a higher percentage of households that receive SNAP benefits, which is super interesting to see.